---
title: Adriano Tanaka Oracle e Linux
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Describe your website here.
disqus_shortname: 
reading_time: true
words_per_minute: 200
logo: images/logo.png
excerpt_separator: "<!--more-->"
url: https://adrianotanaka.github.io
menu:
- title: Home
  url: "/"
- title: Fork
  url: http://github.com/aron-bordin/neo-hpstr-jekyll-theme
- title: Install
  url: http://github.com/aron-bordin/neo-hpstr-jekyll-theme#installation
- title: Tags
  url: "/tags"
- title: Categories
  url: "/categories"
  type: categories
- title: Favorites
  url: "#"
  submenu:
  - title: Code Highlighter
    url: "/intro/code-highlighting-post/"
  - title: Sample Post
    url: "/intro/sample-post/"
owner:
  name: Your name
  site: http://aronbordin.com
  avatar: images/avatar.jpg
  bio: Your bio goes here. It shouldn't be super long but a good two sentences or
    two should suffice.
  email: you@email.com
  twitter: aron_bordin
  github: aron-bordin
twitter: 
social:
- title: github
  url: https://github.com/aron-bordin
- title: linkedin
  url: https://br.linkedin.com/in/aronbordin
- title: youtube
  url: https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg
background: 
google_analytics: 
google_verify: 
bing_verify: 
locale: en_US
future: true
highlighter: rouge
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
float_share: true
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
include:
- ".htaccess"
exclude:
- demo/*
- lib
- config.rb
- Capfile
- config
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules
gems:
- jekyll-paginate
theme: neo-hpstr-jekyll-theme
